spring.application.name=studentapp
spring.datasource.url=jdbc:postgresql://localhost:5432/studentdata
spring.datasource.username=postgres
spring.datasource.password=29122003

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true